import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np

def plot_results(log_folder, title='Learning Curve'):
    """
    Plots the results using the monitor.csv file generated by stable-baselines3
    """
    x, y = [], []
    
    # Find monitor file (usually monitor.csv or monitor.csv.1, etc.)
    monitor_files = [os.path.join(log_folder, f) for f in os.listdir(log_folder) if f.startswith('monitor')]
    
    if not monitor_files:
        print(f"No monitor files found in {log_folder}")
        return

    print(f"Found {len(monitor_files)} monitor files. Plotting...")
    
    # Read data
    data_frames = []
    for file in monitor_files:
        # Skip the first 1 line which is metadata
        print(file)
        df = pd.read_csv(file, skiprows=1)
        data_frames.append(df)
        
    if not data_frames:
        print("No valid data found.")
        return

    # Concat if multiple files (e.g. multiple envs), here we usually just have one
    df = pd.concat(data_frames)
    
    # Sort by time
    df = df.sort_values(by='t')
    
    # Calculate Rolling Averages
    window_size = 50
    if len(df) < window_size:
        window_size = len(df) // 2

    # r = reward, l = length, t = time
    df['reward_smooth'] = df['r'].rolling(window=window_size).mean()
    df['length_smooth'] = df['l'].rolling(window=window_size).mean()

    # Create Plots
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 10))
    
    # Plot Reward
    ax1.set_title(f"{title} - Rewards")
    ax1.plot(df['l'].cumsum(), df['r'], alpha=0.3, color='gray', label='Raw Reward')
    ax1.plot(df['l'].cumsum(), df['reward_smooth'], color='blue', linewidth=2, label=f'Avg Reward ({window_size} ep)')
    ax1.set_ylabel('Episode Reward')
    ax1.set_xlabel('Total Timesteps')
    ax1.legend()
    ax1.grid(True)
    
    # Plot Episode Length
    ax2.set_title(f"{title} - Episode Length")
    ax2.plot(df['l'].cumsum(), df['l'], alpha=0.3, color='gray', label='Raw Length')
    ax2.plot(df['l'].cumsum(), df['length_smooth'], color='green', linewidth=2, label=f'Avg Length ({window_size} ep)')
    ax2.set_ylabel('Steps per Episode')
    ax2.set_xlabel('Total Timesteps')
    ax2.legend()
    ax2.grid(True)
    
    plt.tight_layout()
    plt.show()

import argparse

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("runname")
    args = parser.parse_args()

    # Point this to your logs directory
    LOG_DIR = f"./logs/{args.runname}"
    
    if os.path.exists(LOG_DIR):
        plot_results(LOG_DIR)
    else:
        print(f"Directory {LOG_DIR} does not exist. Run training first.")